### ISSUE TITLE
windows building environment set up failed

### ISSUE THREAD

**Issue by lincleejun** [atom/atom-shell#1140] opened 2015-02-14 06:19 UTC
I clone code from github. and call  ``` c:\Python27\python.exe script\bootstrap.py -v ``` command. but I got an error.

someone could help me to fix the problem?? 

```
details:
C:\work\open_source\atom\as\node_modules\atom-package-manager\lib\auth.js:14
      throw error;
            ^
Error: The specified procedure could not be found.
C:\work\open_source\atom\as\node_modules\atom-package-manager\node_modules\keyta
r\build\Release\keytar.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\work\open_source\atom\as\node_modules\atom-package
-manager\node_modules\keytar\lib\keytar.js:4:12)
    at Object.<anonymous> (C:\work\open_source\atom\as\node_modules\atom-package
-manager\node_modules\keytar\lib\keytar.js:58:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 35, in main
    update_atom_modules('spec')
  File "script\bootstrap.py", line 77, in update_atom_modules
    execute_stdout([apm, 'install'])
  File "C:\work\open_source\atom\as\script\lib\util.py", line 152, in execute_st
dout
    raise e
subprocess.CalledProcessError: Command '['C:\\work\\open_source\\atom\\as\\node_
modules\\atom-package-manager\\bin\\apm.cmd', 'install']' returned non-zero exit
 status 8
```

**Comment by akrieger** [comment] 2015-02-17 23:20
I am getting the same error.

**Comment by akrieger** [comment] 2015-02-17 23:27
Might be related to https://github.com/atom/atom-shell/issues/963

**Comment by akrieger** [comment] 2015-02-17 23:33
@lincleejun, can you try running 'npm install keytar' and then re-trying the bootstrap script? That seems to have worked for me.

**Comment by akrieger** [comment] 2015-02-17 23:34
D'oh, spoke too soon. Looked like it got farther but then failed again.

**Comment by akrieger** [comment] 2015-02-18 00:51
So far I have tried:
Switching from 64bit to 32bit node (oops, but didn't help).
Uninstalling all .NET frameworks, reinstalling 4.5.1 SDK and runtime.
Installing VS 2013 redists.
Installing VS 2012 Express (but compiling with VS 2013 installed as well. Uninstalling 2013 now).
Installing Windows 8.1 SDK.

So far, nothing. Dependency analysis shows a handful of missing .dlls, but those are missing on every .exe I check, so it's not that.

**Comment by paulcbetts** [comment] 2015-02-18 01:25
You do need 32-bit Node, you also need Node 0.10.x; if your node version reports 0.12.x, you are Too Hip And With It™ and need to go back to 0.10.x

**Comment by paulcbetts** [comment] 2015-02-18 01:30
Having >1 VS installation will also cause you tears, you really just need *only* VS2013

**Comment by akrieger** [comment] 2015-02-18 01:46
Ok, I'll revert to Node 0.10.x, remove 2012, and re-install 2013, and report back.

If the issue is Node 0.10.x vs. 0.12, then it would help having that specified in the build instructions, as opposed to simply 32-bit.

**Comment by akrieger** [comment] 2015-02-18 03:11
Alright, after installing node 0.10.35, VC Community 2013, I get hung up on a different error on the same step.

```
c:\open\atom-shell\node_modules\atom-package-manager\bin\apm.cmd install
Installing modules failed
npm WARN package.json atom-shell-specs@0.1.0 No description
npm WARN package.json atom-shell-specs@0.1.0 No repository field.
npm WARN package.json atom-shell-specs@0.1.0 No README data
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\open\\atom-shell\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\open\\atom-shell\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig
" "c:\\open\\atom-shell\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\akrieger\\.atom\\.apmrc" "install" "--target=0.21.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18

npm ERR! uid must be an unsigned int
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <http://github.com/npm/npm/issues>
None
Traceback (most recent call last):
  File "script/bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 35, in main
    update_atom_modules('spec')
  File "script/bootstrap.py", line 77, in update_atom_modules
    execute_stdout([apm, 'install'])
  File "c:\open\atom-shell\script\lib\util.py", line 152, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['c:\\open\\atom-shell\\node_modules\\atom-package-manager\\bin\\apm.cmd', 'install']' returned non-zero exit status 1
```

I'll mess with it more in the morning. This is after doing a `git clean -fdx; rm -rf vendor/*; git reset --hard HEAD;`

**Comment by akrieger** [comment] 2015-02-18 03:13
http://pastebin.com/vWh5S5RN is the contents of spec/npm-debug.log

**Comment by paulcbetts** [comment] 2015-02-18 03:46
@akrieger After you did the clean, you reran bootstrap.py && build.py?

**Comment by akrieger** [comment] 2015-02-18 04:37
Yep, reran bootstrap.py. The error was during bootstrap.py.

I have full perms to C:\open. I am not running as an elevated user (running inside the git shell from http://git-scm.com/download/win).

ls -la output: http://pastebin.com/eewvCj3U

**Comment by akrieger** [comment] 2015-02-18 04:38
I guess I could re-clone atom-shell and see if it still repro's.

**Comment by akrieger** [comment] 2015-02-18 04:42
When I do a very-clean build, I get this error the first time running bootstrap.py:

```
  Finished generating code
  runas.vcxproj -> c:\open\atom-shell\node_modules\runas\build\Release\\runas.node
runas@2.0.0 ..\..\node_modules\runas
└── nan@1.6.1
c:\Program Files\Python27\python.exe c:\open\atom-shell\script\update.py
Download directxsdk     1423225  [100.0%]
Download vs2012_crt      772170  [100.0%]
c:\open\atom-shell\node_modules\atom-package-manager\bin\apm.cmd install
Installing modules failed
> runas@2.0.0 install c:\open\atom-shell\spec\node_modules\runas
> node-gyp rebuild


npm WARN package.json atom-shell-specs@0.1.0 No description
npm WARN package.json atom-shell-specs@0.1.0 No repository field.
npm WARN package.json atom-shell-specs@0.1.0 No README data
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\open\\atom-shell\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\open\\atom-shell\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig
" "c:\\open\\atom-shell\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\akrieger\\.atom\\.apmrc" "install" "--target=0.21.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
None
Traceback (most recent call last):
  File "script/bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 35, in main
    update_atom_modules('spec')
  File "script/bootstrap.py", line 77, in update_atom_modules
    execute_stdout([apm, 'install'])
  File "c:\open\atom-shell\script\lib\util.py", line 152, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['c:\\open\\atom-shell\\node_modules\\atom-package-manager\\bin\\apm.cmd', 'install']' returned non-zero exit status 1

akrieger@AKRIEGER-X1 /c/open/atom-shell (master)
```

**Comment by akrieger** [comment] 2015-02-18 04:43
I got the above error about 'uid must be an unsigned int' running bootstrap a second time.

**Comment by akrieger** [comment] 2015-02-18 04:47
Aaaand on a clean clone and bootstrap I get this error.

```
c:\Program Files\Python27\python.exe c:\open\atom-shell\script\update.py
Download directxsdk     1423225  [100.0%]
Download vs2012_crt      772170  [100.0%]
c:\open\atom-shell\node_modules\atom-package-manager\bin\apm.cmd install
Installing modules failed
> runas@2.0.0 install c:\open\atom-shell\spec\node_modules\runas
> node-gyp rebuild


npm WARN package.json atom-shell-specs@0.1.0 No description
npm WARN package.json atom-shell-specs@0.1.0 No repository field.
npm WARN package.json atom-shell-specs@0.1.0 No README data
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 6.2.9200
npm ERR! argv "c:\\open\\atom-shell\\node_modules\\atom-package-manager\\bin\\\\node.exe" "c:\\open\\atom-shell\\node_modules\\atom-package-manager\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig
" "c:\\open\\atom-shell\\node_modules\\atom-package-manager\\.apmrc" "--userconfig" "C:\\Users\\akrieger\\.atom\\.apmrc" "install" "--target=0.21.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! runas@2.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@2.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls runas
npm ERR! There is likely additional logging output above.
None
Traceback (most recent call last):
  File "script/bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 35, in main
    update_atom_modules('spec')
  File "script/bootstrap.py", line 77, in update_atom_modules
    execute_stdout([apm, 'install'])
  File "c:\open\atom-shell\script\lib\util.py", line 152, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['c:\\open\\atom-shell\\node_modules\\atom-package-manager\\bin\\apm.cmd', 'install']' returned non-zero exit status 1

akrieger@AKRIEGER-X1 /c/open/atom-shell (master)
```

**Comment by akrieger** [comment] 2015-02-18 04:49
Curiously, npm list shows this:

```
...
│ ├─┬ tough-cookie@0.12.1
│ │ └── punycode@1.3.2
│ └── tunnel-agent@0.4.0
└─┬ runas@2.0.0 extraneous
  └── nan@1.6.1

npm ERR! extraneous: runas@2.0.0 c:\open\atom-shell\node_modules\runas
npm ERR! not ok code 0

akrieger@AKRIEGER-X1 /c/open/atom-shell (master)
```

**Comment by akrieger** [comment] 2015-02-18 05:04
Just for fun, I'm going to install node into C:\open instead of into program files and see if things magically stop failing.

**Comment by paulcbetts** [comment] 2015-02-18 05:04
Wait, are you running under Bash? What happens if you run under 'cmd'?

**Comment by akrieger** [comment] 2015-02-18 05:15
Huh. It magically just works if I run it under powershell.

**Comment by akrieger** [comment] 2015-02-18 05:16
In theory the bash shell should have all the same path semantics as powershell. But maybe not? Interactions with env may be weird in the git bash.

**Comment by akrieger** [comment] 2015-02-18 05:17
Ok, well. @lincleejun, try node 0.10.x. @paulcbetts, can you update the docs to specify node 0.10.x as well as 32-bit?

**Comment by akrieger** [comment] 2015-02-18 05:21
Now I just get generic build errors. Sigh. I can open a new issue for those assuming I can't resolve them.

**Comment by frankhale** [comment] 2015-02-18 05:32
The Windows build doc already says 32bit Node is required to build. It's not totally clear why we need to still use Node 0.10.x to bootstrap since at least the latest version of Atom-Shell uses io.js internally. I just tried bootstrapping on io.js 1.2.0 and it failed. I'm sure there is a good explanation for this that I am not aware of. I always use the Visual Studio 2013 command prompt to build and have never had a problem as long as I color within the lines. Just saying.

https://github.com/atom/atom-shell/blob/master/docs/development/build-instructions-windows.md

**Comment by akrieger** [comment] 2015-02-18 05:37
Yep, fair. I also just scrolled to the end of the build instructions and saw the message about exactly the second error I had, using git bash.

Sorry, new to Windows dev :) I thought the 'git bash' that ships with the git install is just a wrapper around cmd.exe that adds some stuff to the path, I didn't realize it was actually some weird bash port.

Like I mentioned earlier, I got more hung up more on the node 0.10.x requirement than the 32 vs 64 bit problem. The 'oops' part of my comment was because I re-read the instructions to use 32 bit, so that was the first thing I tried and it didn't help.

**Comment by paulcbetts** [comment] 2015-02-18 05:48
@akrieger It shouldn't be this hard, but a lot of the fragility is because of Chrome, but the rest should be on us to make it fall over less. Thanks for putting up with the frustration

**Comment by lllama** [comment] 2015-02-20 14:41
I'm also getting build errors. I'm using Windows 8.1 with VS 2013 community edition. From the Developers' Tools Command Prompt with a clean checkout:

```
C:\atom-shell>python --version
Python 2.7.6

C:\atom-shell>node -v
v0.10.36

C:\atom-shell>python script\bootstrap.py
C:\atom-shell>python script\build.py
ninja: Entering directory `out\Release'
[51/955] CC obj\vendor\node\deps\uv\src\win\libuv.fs.obj
c:\atom-shell\vendor\node\deps\uv\src\win\fs.c(809) : warning C4210: nonstandard extension used : function given file scope
[353/955] CC obj\vendor\node\deps\open...enssl\crypto\dso\openssl.dso_win32.obj
c:\atom-shell\vendor\node\deps\openssl\openssl\crypto\dso\dso_win32.c(300) : warning C4055: 'type cast' : from data pointer 'void *' to function pointer 'DSO_FUNC_TYPE'
[674/955] CXX obj\atom\common\atom_lib.node_bindings.obj
FAILED: ninja -t msvc -e environment.x86 -- "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\amd64_x86\cl.exe" /nologo /showIncludes /FC @obj\atom\common\atom_lib.node_bindings.obj.rsp /c ..\..\atom\common\node_bindings.cc /Foobj\atom\common\atom_lib.node_bindings.obj /Fdobj\atom_lib.cc.pdb
c:\atom-shell\atom\common\node_bindings.cc(181) : error C2065: 'Lprocess_type' : undeclared identifier
c:\atom-shell\atom\common\node_bindings.cc(182) : error C2228: left of '.Append' must have class/struct/union
c:\atom-shell\atom\common\node_bindings.cc(183) : error C2228: left of '.Append' must have class/struct/union
[674/955] CXX obj\atom\common\atom_lib.common_message_generator.obj
ninja: build stopped: subcommand failed.
```

**Comment by lllama** [comment] 2015-02-20 14:52
A little more investigation. These are the offending lines:
```
  const char* process_type = is_browser_ ? "browser" : "renderer";
  base::FilePath resources_path = GetResourcesPath(command_line, is_browser_);
  base::FilePath script_path =
      resources_path.Append(FILE_PATH_LITERAL("atom.asar"))
                    .Append(FILE_PATH_LITERAL(process_type))
                    .Append(FILE_PATH_LITERAL("lib"))
                    .Append(FILE_PATH_LITERAL("init.js"));

```
If I change `.Append(FILE_PATH_LITERAL(process_type))` to `.Append(FILE_PATH_LITERAL("browser"))` then the build succeeds (not tried with "renderer"). Could this be `const char*` vs literal UTF8?

**Comment by akrieger** [comment] 2015-02-20 22:04
That is a different problem than the one I and @lincleejun were having. See https://github.com/atom/atom-shell/pull/1147

**Comment by lllama** [comment] 2015-02-20 22:46
@akreiger - apologies for hijacking the thread. Your pull request appears to solve my problem, so thanks for that. In case anyone else stumbles upon the issue I had, I can now do a successful build using:

- node 0.10.36 (32-bit)
- python 2.7.6
- Visual Studio 2013 Community Edition

The build worked in the "Developer Command Prompt for VS2013", which may not be present in your start screen if you're using 8.1 (I had to hunt it out).

**Comment by lincleejun** [comment] 2015-02-25 03:06
OMG, so many comments :)... But thanks guys, it help me fix the building problem....thx...

**Comment by deepak1556** [comment] 2015-02-27 12:13
using node v0.12 (64-bit) and built atom-shell successfully after making changes to apm download v0.12 node https://github.com/deepak1556/apm and applying @akrieger changes to `FILE_PATH_LITERAL` macro on windows . Is this good ? ;)
![atom-shell](https://cloud.githubusercontent.com/assets/964386/6412288/d1000bb8-bea7-11e4-8310-acd2a1253805.jpg)

**Comment by zcbenz** [comment] 2015-02-28 00:06
#1147 has been fixed and it seems that op's problem has also been solved, so I'm closing this.

**Closed by zcbenz** 2015-02-28 00:06 UTC
