### ISSUE TITLE
Webview need a dispose() method or similar

### ISSUE THREAD

**Issue by bpasero** [atom/atom-shell#1004] opened 2015-01-13 15:45 UTC
This is a follow up from https://github.com/atom/atom-shell/issues/885. When I created > 10 webviews in my Atom app, I get this stack:

(node) warning: possible EventEmitter memory leak detected. 11 render-view-deleted listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at EventEmitter.addListener (events.js:179:15)
    at EventEmitter.once (events.js:204:8)
    at createGuest (...\resources\atom\browser\lib\guest-view-manager.js:39:14)
    at EventEmitter.<anonymous> (...\resources\atom\browser\lib\guest-view-manager.js:95:66)
    at EventEmitter.emit (events.js:118:17)
    at EventEmitter.<anonymous> (...\resources\atom\browser\api\lib\web-contents.js:86:23)
    at EventEmitter.emit (events.js:118:17)

I am recreating webviews due to bug #764.

The webview tag must expose a dispose method for me to clear its listeners.

**Comment by zcbenz** [comment] 2015-01-13 19:32
Can you share some code to produce this?

**Comment by bpasero** [comment] 2015-01-14 17:47
Nothing special, just put 11 webview tags on a page and you got it.

**Comment by bwin** [comment] 2015-01-14 20:06
Doesn't happen in 0.20.5.

**Comment by zcbenz** [comment] 2015-01-14 20:09
@bpasero If you put 11 `<webview>` tags in the page at the same time without destroying any, then the warning is expected.

**Comment by bwin** [comment] 2015-01-14 20:10
@zcbenz I tested and it does even appear if you create 10, then delete 1 and create another one (so that there are 10 in total). BUT this does just happen in 0.19.5.

**Comment by bwin** [comment] 2015-01-14 20:16
You can reproduce with this gist https://gist.github.com/bwin/dfba1b251a7b09b83618
But I think we should close it, since it doesn't happen on current atom-shell.

**Comment by zcbenz** [comment] 2015-01-14 20:17
@bwin :+1:

**Closed by zcbenz** 2015-01-14 20:17 UTC

**Comment by bpasero** [comment] 2015-01-15 07:42
I tried on a 0.19.x version and will verify with latest, thanks.
