### ISSUE TITLE
Webview: display:none seems to cause it to be garbage collected and using it after that will crash Atom-Shell

### ISSUE THREAD

**Issue by frankhale** [atom/atom-shell#764] opened 2014-10-31 20:13 UTC
OS: Windows 8.1 x64
Atom-Shell: 0.19

Sorry for all the editing and deleting of my previous reports but the issue is morphing and I've narrowed it down. Apparently the webview is garbage collected when you set it's CSS display property to none. If you do this then you cannot use the webview again and if you try to set it's src it will crash Atom-Shell.

```html
<!DOCTYPE html>
<html>
<head>
  <title>webview crash test</title>
</head>
<body>
  <webview id="web" style="width:100%;height:100%;position:absolute;"></webview>
  <script>
    window.onload = function() {
      var web = document.getElementById("web");
      web.src = "http://msn.com";
    };
  </script>
</body>
</html>
```

Reproduce the crash:

In your main.js make sure you have it open the dev tools once it creates a new browser window. Use the dev tools to set the CSS display property for the webview to none. Set the src of the webview using the console. Observe Atom-Shell crash.

Now a point of clarification: This sounds convoluted but I was using display:none to hide the webview, set the source and then show it in my app. I should have been using visibility:hidden instead. My UI is just set up to show the webview in the entire width/height of the window but underneath of it there is a list of links to choose from. This is the reasoning I found this issue. Using visibility:hidden makes the crashing go away.

Question, does calling display:none on the webview cause the webview to be garbage collected?

**Comment by zcbenz** [comment] 2015-01-30 01:39
I can confirm this has been fixed in v0.21.0.

**Comment by frankhale** [comment] 2015-01-30 01:39
Awesome! Thank you!!!

**Closed by zcbenz** 2015-01-30 01:39 UTC
Labels: bug, crash, webview

**Comment by mark-hahn** [comment] 2015-01-30 01:40
Ditto.

**Comment by mark-hahn** [comment] 2015-01-31 00:15
I'm using Atom 0.176.0.  It uses v 0.21.0, right?  Unfortunately I'm still seeing the problem.  If I go to the webview element in chrome inspector and add `display:none` the Atom window crashes immediately.

windows 8.1
Atom 0.176.0
apm  0.128.0
npm  2.3.0
node 0.10.35
python 2.7.8
git 1.7.11.msysgit.1
visual studio 2013

**Comment by zcbenz** [comment] 2015-01-31 00:17
@mark-hahn It is still using v0.20.x, the v0.21.0 ships Chrome 40 so we want to have more tests before publishing it in Atom.

**Comment by mark-hahn** [comment] 2015-01-31 00:32
Thanks.  How do I find what atom-shell version is being used in Atom?

**Comment by zcbenz** [comment] 2015-01-31 00:33
`process.versions['atom-shell']`

**Comment by mrgrimmig** [comment] 2017-07-02 19:50
I realised that the problem is still there, if you show a webview, which didn't load an url so far.
How to reproduce:

1. attach a new webview without src attribute
2. set display to none
3. set display to flex (or whatever)

btw. it doesn't matter if a change the style of the webview or its parent element.
