### ISSUE TITLE
Web View not loaded on Reload

### ISSUE THREAD

**Issue by raeesiqbal** [atom/atom-shell#1230] opened 2015-03-10 21:50 UTC
Index.html
```html
<webview id="MainPage" src="https://www.google.com/"></webview>
<script src="main.js"></script>
```
Main.js

```js
$Document.ready(function(){
  $Document.on("keydown", function(e){
    if (e.ctrlKey && e.altKey && e.which === 82) {
        window.location.reload();
      }
  });
});
```

The web view renders perfectly on first start.
But when the window is reloaded via CTRL + ALT + R
The webview remains blank.

**Comment by steelbrain** [comment] 2015-03-12 12:50
It's not just on reload.
WebView just turns blank. like randomly.
and then if we open dev tools of the private window and then close them, or change the width/height of it, it re-appears.

**Comment by steelbrain** [comment] 2015-03-12 14:51
Duplicate of #1110

**Comment by zcbenz** [comment] 2015-03-13 19:51
Close as duplicate of #1110, thanks @steelbrain!

**Closed by zcbenz** 2015-03-13 19:51 UTC
