### ISSUE TITLE
Write image to clipboard?

### ISSUE THREAD

**Issue by CharlieHess** [atom/atom-shell#1007] opened 2015-01-14 23:31 UTC
Is there a supported way to write an image using the [`clipboard`](https://github.com/atom/atom-shell/blob/master/docs/api/clipboard.md) API? I've tried writing a data URL using `writeText` (similar to [this](https://developer.mozilla.org/en-US/Add-ons/SDK/High-Level_APIs/clipboard)) but that isn't cutting it. Perhaps the `type` parameter is involved but the documentation isn't clear as to what that should be.

**Comment by zcbenz** [comment] 2015-01-14 23:38
There is no way to access images in clipboard for now.

Closing this because it is a duplicate of https://github.com/atom/atom-shell/issues/580.

**Closed by zcbenz** 2015-01-14 23:38 UTC
