### ISSUE TITLE
Tray balloon not showing on Windows when icon option is provided

### ISSUE THREAD

**Issue by jorangreef** [atom/atom-shell#1394] opened 2015-04-09 14:44 UTC
Displaying a tray balloon without an icon option works on Windows.

But adding an icon option (using a path to an image [which works fine for the tray icon itself], or using an instance of NativeImage) causes the tray balloon to not show at all.

**Comment by paulcbetts** [comment] 2015-04-12 01:10
This means for some reason that the image can't be loaded, so the entire thing bails out - you can see the message in the debug logs.

**Comment by tommoor** [comment] 2015-04-12 01:18
@jorangreef I had a similar problem, make sure it's not this: https://github.com/atom/atom-shell/issues/1299#issuecomment-86325222

**Comment by zcbenz** [comment] 2015-04-13 09:06
I'm closing since it doesn't seem to be a bug. I'll reopen if there is a reproducible example.

**Closed by zcbenz** 2015-04-13 09:06 UTC

**Comment by jorangreef** [comment] 2015-04-13 10:34
Thanks Tom. I'm passing a normal path. This same path works when setting the tray icon, but it keeps the balloon from showing if passed as an option.

**Comment by jorangreef** [comment] 2015-04-13 10:38
I've created a reproducible test app for Windows.

It's attached here as a zip of the app directory and just needs to be added to a Windows build.

When run it will show a Pac-Man icon in the tray, and then try and show a balloon using the same icon. This will fail silently and the balloon will not display at all.

10 seconds later it will try and show a balloon without an icon and this will succeed.

20 seconds later it will try and show a balloon with the same tray icon and this will fail silently again.

https://www.dropbox.com/s/adeb3sjwjtxdudn/app.zip?dl=0

**Comment by zcbenz** [comment] 2015-04-13 11:07
@jorangreef I tried with your app, from the log Windows API refuses to show the balloon with your icon, it didn't give the reason, I replaced the icon with Atom's logo, then it showed successfully. I wonder if it is because your icon is too small.

**Comment by jorangreef** [comment] 2015-04-13 11:36
Thank you for your help Cheng.

I tried with a 32x32 icon and that works. 24x24 also fails so perhaps 32x32 is the minimum.
