### ISSUE TITLE
Webgl in linux no available?

### ISSUE THREAD

**Issue by m1ga** [atom/atom-shell#1277] opened 2015-03-21 22:14 UTC
using http://html5test.com/

normal chrome browser: YOUR BROWSER SCORES 518 OUT OF 555 POINTS (WebGL 3D graphics
Yes )

atom-shell: YOUR BROWSER SCORES 497 OUT OF 555 POINTS (WebGL 3D graphics
No )

on both: "You are using Chrome 41 on Linux".

atom-shell: v0.22.1
fedora linux

How can I enable webgl?

**Comment by bwin** [comment] 2015-03-21 22:35
RTFM - When searching this repo for "webgl" (filter by markdown, to get the docs) you will find the docs for the BrowserWindow-constuctor.
https://github.com/atom/atom-shell/blob/master/docs/api/browser-window.md#new-browserwindowoptions
There's a flag `webgl` in `web-preferences`. (But I don't know if it works with this flag.)

**Comment by bwin** [comment] 2015-03-21 22:39
BTW we could include the default values for these flags in the docs...

**Comment by mcdermed** [comment] 2015-03-21 22:40
Your card may be blacklisted or you may not have the correct drivers. Webgl
is working fine on Linux

**Comment by m1ga** [comment] 2015-03-21 22:42
~~~
var app = require('app'); // Module to control application life.
var BrowserWindow = require('browser-window'); // Module to create native browser window.

// Report crashes to our server.
require('crash-reporter').start();

var mainWindow = null;

app.on('window-all-closed', function() {
    if (process.platform != 'darwin')
        app.quit();
});

app.on('ready', function() {
    mainWindow = new BrowserWindow({
        "width": 1024,
        "height": 768,
        'web-preferences': {
            'web-security': false,
            "webgl": true
        }
    });
    mainWindow.loadUrl('http://html5test.com/');
    mainWindow.on('closed', function() {
        mainWindow = null;
    });
});
~~~

no difference. And I thought it was enabled by default in an earlier commit

**Comment by bwin** [comment] 2015-03-21 22:44
@m1ga Ok, i never used it, was just searching the docs for you.

> Your card may be blacklisted or you may not have the correct drivers.

That's unlikely, when it's works for you in Chrome.

**Comment by m1ga** [comment] 2015-03-21 22:46
@bwin 
NVIDIA Corporation GT216GLM [Quadro FX 880M] (rev a2)
with Nouveau driver. But like you said, chrome is working fine just atom-shell is saying it can't use webgl

**Comment by bwin** [comment] 2015-03-21 22:49
Sorry, I could only test on Ubuntu, but that's likely irrelevant since mcdermed already confirmed that it works (for him) on linux...

**Comment by m1ga** [comment] 2015-03-21 22:51
~~~
"experimental-features":true,
"experimental-canvas-features":true
~~~
gives me 505 points in the html5 test but still no webgl. Maybe its the nouveau driver. I'll have a look if i can install them to check

**Comment by mcdermed** [comment] 2015-03-21 22:52
Yep. I'm using the Nvidia proprietary drivers.

**Comment by bwin** [comment] 2015-03-21 23:21
@m1ga BTW sorry for the "RTFM `web-preferences`"-advice.
I searched, this came up, you hadn't mentioned it, case closed (I thought).

**Comment by m1ga** [comment] 2015-03-21 23:48
no problem at all! Didn't try it so it was worth a try. Still trying to get nvidia drivers to run...

**Comment by m1ga** [comment] 2015-03-22 00:11
ok, the nouveau driver is the problem! The proprietary nvidia driver is working!
Its supported by chrome but not by chromium.

**Comment by bwin** [comment] 2015-03-22 00:14
Thanks for reporting back. If others can confirm it (in case it was not caused by some special circumstances on your system) this should be mentioned in the docs.

**Comment by bwin** [comment] 2015-03-22 00:17
I'll try to confirm it in the next days.

**Comment by m1ga** [comment] 2015-03-22 00:22
old chromium issue: https://code.google.com/p/chromium/issues/detail?id=121183
~~~
It has long been able to run WebGL in both Chromium and Firefox, but Chromium seems to blacklist WebGL for Nouveau/Gallium3D. Forcing WebGL to be enabled yields success.
~~~

**Comment by zcbenz** [comment] 2015-03-23 02:01
@m1ga Does appending `--ignore-gpu-blacklist` in command line work for you?

**Comment by zcbenz** [comment] 2015-04-08 01:45
I'm closing this unless there is more information provided.

**Closed by zcbenz** 2015-04-08 01:45 UTC

**Comment by m1ga** [comment] 2015-04-08 16:15
sorry, can't go back to nouveau at the moment.

**Comment by frozeman** [comment] 2016-01-27 08:53
@zcbenz is it possible to create a binary with `ignore-cpu-blacklist` enabled by default? Seems mainly to be an linux issue for me, and i would like to enable it by default.

**Comment by zcbenz** [comment] 2016-01-27 12:24
You can try using `app.commandLine.appendSwitch` to append it.

Also the blacklist exists for a reason, force ignoring it is going to cause rendering issues and even crashes.

**Comment by yagamiram** [comment] 2016-03-08 02:58
I'm facing the same problem in Virtual Box - Ubuntu (14.04) and latest chromium. Is there any solution for this ?

**Comment by ionphractal** [comment] 2017-04-22 20:00
@yagamiram 
In my case setting `app.commandLine.appendSwitch('ignore-gpu-blacklist', 'true')` directly after `require('electron')` in `main.js` helped, but there are various other settings you could test:
```
app.commandLine.appendSwitch('enable-gpu-rasterization', 'true')
app.commandLine.appendSwitch('enable-zero-copy', 'true')
app.commandLine.appendSwitch('disable-software-rasterizer', 'true')
app.commandLine.appendSwitch('enable-native-gpu-memory-buffers', 'true')
```
Nice overview of Chromium command line switches: http://peter.sh/experiments/chromium-command-line-switches/

And of course, as mentioned above, adding the experimental features to the options object you give as arguments to create the browser window.
```
options = {
	webgl: true,
	experimentalFeatures: true,
	experimentalCanvasFeatures: true,
	offscreen: true,
})
const mainWindow = new electron.BrowserWindow(options)
```
You can also point Electron to load `chrome://gpu/` to see what's enabled and what not.
