### ISSUE TITLE
Tray API isn't compatible with ASAR

### ISSUE THREAD

**Issue by paulcbetts** [atom/atom-shell#1118] opened 2015-02-10 02:13 UTC
Tray API seems to throw TypeErrors when the path passed in is an ASAR path.

**Comment by bwin** [comment] 2015-02-10 10:24
dup of #1006 ?

**Comment by zcbenz** [comment] 2015-02-10 13:14
Yeah it is a duplicate of #1006.

**Closed by zcbenz** 2015-02-10 13:14 UTC
