### ISSUE TITLE
Option to open dev tools detached

### ISSUE THREAD

**Issue by tommoor** [atom/atom-shell#1300] opened 2015-03-25 21:49 UTC
If your app isn't a fullscreen app like the atom editor, but is perhaps a tray app or has a narrow tall window then the attached dev tools are unusably narrow. 

It would be great to have an option for the openDevTools method to be able to start it detached from the current window. eg something like:

```javascript
browserWindow.openDevTools({detached: true})
```

**Comment by bwin** [comment] 2015-03-26 01:28
This would be convenient, but note that once you detached the devtools manually, the next call to `openDevTools` will show them detached (even after restarting the app). At least on Windows. (Tested with Atom-Shell 0.22.1)

**Comment by bwin** [comment] 2015-03-26 01:34
Oh yeah, Frank's right. Dupe of #1135. There's also a hacky work-around.

**Comment by zcbenz** [comment] 2015-03-26 03:42
I'm closing this and reopening #1135.

**Closed by zcbenz** 2015-03-26 03:42 UTC
