### ISSUE TITLE
Get screen information for other windows

### ISSUE THREAD

**Issue by iamdriz** [atom/atom-shell#993] opened 2015-01-09 16:36 UTC
According to the docs: https://github.com/atom/atom-shell/blob/master/docs/api/screen.md you can access the primary display but they don't mention anything about managing other screens.

Basically I want to load two BrowserWindows and tell them to appear on the different screens (when a user has more than one screen available).

In Adobe AIR I did something like:

~~~
var largestScreen = null;

if(air.Screen.screens.length > 1) {

	for( index = 0; index < air.Screen.screens.length; ++index) {
		var currentScreen = air.Screen.screens[index];
		if( largestScreen == null ){
			largestScreen = currentScreen;  
		}
		else{
			//Defining largest screen as biggest total area.
			var currentArea = currentScreen.bounds.width * currentScreen.bounds.height;
			var largestArea = largestScreen.bounds.width * largestScreen.bounds.height;
			if(currentArea > largestArea) {
				largestScreen = currentScreen;
			}
		}
	}

} else {

	// Show error that you need a projector screen
	alert('You need more than one screen to run this application.');

}
~~~

And then I could target a window bounds for the windows.

Is it possible to achieve something similar in atom-shell?

**Comment by zcbenz** [comment] 2015-01-09 21:46
This is a duplicate of 780.

**Closed by zcbenz** 2015-01-09 21:46 UTC
