### ISSUE TITLE
how to take screenshot?

### ISSUE THREAD

**Issue by loveencounterflow** [atom/atom-shell#954] opened 2014-12-25 20:23 UTC
i'm trying to take a screen shot of my first atom-shell app; i'm using https://github.com/dougnukem/hello-atom to get started. 

in my `index.html` i put the following code [as recommended by the `remote` docs](https://github.com/atom/atom-shell/blob/b84226244d840a1ec8410b2dbce03b9de3f5c7b1/docs/api/remote.md):

```html
    <script>
      var remote = require('remote');
      remote.getCurrentWindow().capturePage(function(buf) {
        remote.require('fs').writeFile('/tmp/screenshot.png', buf, function(err) {
          console.log(err);
        });
      });
      </script>
```

however, the `*.png` is always 0 bytes long. is the API broken or did i miss something?

**Comment by zcbenz** [comment] 2015-01-02 20:22
I'm closing this unless there is more information, it also seems that it was caused by using an old version of atom-shell.

**Closed by zcbenz** 2015-01-02 20:22 UTC

**Comment by loveencounterflow** [comment] 2015-01-02 20:24
ok fine. sorry i've been so silent—absorbed into other things. cheers.

**Comment by KirillUrgant** [comment] 2017-03-23 07:03
@loveencounterflow  use buf.toJpeg(), buf.toPng()..
