### ISSUE TITLE
Fullscreen window with frame shows empty title

### ISSUE THREAD

**Issue by iamdriz** [atom/atom-shell#1057] opened 2015-01-26 20:36 UTC
If you have a fullscreen window on OS X Yosemite then you see **a** window title all the time:

![screen shot 2015-01-26 at 20 32 37](https://cloud.githubusercontent.com/assets/801252/5907914/dbd92086-a59a-11e4-9876-d6402eec525b.png)

Notice I say **a** window title, as if you hover the top of the screen, you then get the window title with the buttons and name of the window...

![screen shot 2015-01-26 at 20 34 58](https://cloud.githubusercontent.com/assets/801252/5907920/e9fcc938-a59a-11e4-8102-4a20d6b349d3.png)

Code:
~~~

app.on('ready', function() {
	
	var Screen = require('screen');
	
	var size = Screen.getPrimaryDisplay().size;

	mainWindow = new BrowserWindow({
	  'width': size.width,
	  'height': size.height,
	  'fullscreen': true,
	  'frame': true,
	  'resizable': false,
	  'auto-hide-menu-bar': true
	});

});

~~~

**Comment by zcbenz** [comment] 2015-01-26 20:57
Can you share the whole code? I cannot reproduce with this.

**Comment by iamdriz** [comment] 2015-01-26 21:01
I wonder if it's because of the use of size rather than workAreaSize...

**Comment by zcbenz** [comment] 2015-03-16 11:12
I'm closing this unless there is more information.

**Closed by zcbenz** 2015-03-16 11:12 UTC
