### ISSUE TITLE
Hide mouse cursor in app?

### ISSUE THREAD

**Issue by raskolnikoov** [atom/atom-shell#1222] opened 2015-03-09 11:16 UTC
I'm creating a touched based app with atom-shell. Is it possible to hide the mouse curosor? I've tested with:

cursor: none;
   -moz-user-select: none;
   -khtml-user-select: none;
   -webkit-user-select: none;
   -ms-user-select: none;
   user-select: none;

on the body element but it dosent seems to work. But It does work in my Google Chrome.

**Comment by YuriSolovyov** [comment] 2015-03-09 19:48
cursor: none ?

**Comment by zcbenz** [comment] 2015-03-10 00:23
Can you share a simple page that shows this problem?

**Comment by raskolnikoov** [comment] 2015-03-10 13:00
<code>
<!DOCTYPE html>
<html>
  <head>
    <title>Loading ...</title>
    <meta http-equiv="refresh" content="2; url=http://localhost:9090" />
    <style>
    	
      * { 
  		  -webkit-box-sizing: border-box;
  		  -moz-box-sizing: border-box;
  		  box-sizing: border-box;
        outline: none;
  		}

    	body{
    		overflow: hidden;
    		background: #333237;
        cursor: none;
       -moz-user-select: none;
       -khtml-user-select: none;
       -webkit-user-select: none;
       -ms-user-select: none;
       user-select: none;
    	}

      body::selection { background: transparent; }
      body::-moz-selection { background: transparent; }

    	#logo{
    		width: 100%;
    		height: 100%;
    		display: block;
    		position: absolute;
    		top: 0;
    		left: 0;
    		background: transparent url('logo.png') center center no-repeat;
    	}

    </style>
  </head>
  <body>
  	<div id="logo"></div>
  </body>
</html>
</code>

Here is my index.html file that is started when my atom-shell app starts. After 2 seconds it redirects to a webserver that also has the css style body properties set as above to hide the mouse cursor and make the content of the html-page not selectable.

The hiding of the mouse cursor dosent work when I runt this css style properties in the atom-shell app but it does work when I run the same code in for example Google Chrome.

**Comment by zcbenz** [comment] 2015-03-10 20:18
Do you mean it the redirect the mouse cursor can not be hidden?

I can not reproduce with your page, it is very likely that the problem is in other parts of you app.

**Comment by raskolnikoov** [comment] 2015-03-17 22:26
No. Both the index.html file that is first shown when the app starts and the html that is redirected to after two seconds dosent hide the mouse cursor. But if I run the same files in google chrome the mouse is hidden. So any idea?

**Comment by zcbenz** [comment] 2015-03-19 03:44
Can you provide a example that __without__ redirecting? And what's the version of atom-shell you were using?

**Comment by zcbenz** [comment] 2015-04-08 01:45
I'm closing this unless there is more information provided.

**Closed by zcbenz** 2015-04-08 01:45 UTC

**Comment by Ivshti** [comment] 2015-06-04 07:34
@zcbenz I am also finding this issue, but only under Windows.

I think it's platform-specific. The same cursor: none; code that works under OS X doesn't on Windows :)

**Comment by nebnes** [comment] 2015-06-04 13:31
I am agree it's work well on osx but I can turn the cursor off under windows 8

**Comment by Ivshti** [comment] 2015-06-04 15:14
@nebnes  - @zcbenz  was right to close this. 

cursor: none isn't supported according to this http://delphic.me.uk/controllingthecursor.html but you can easily use an image

**Comment by graphnode** [comment] 2015-07-04 03:34
@Ivshti
Actually `cursor: none` works correctly on Chrome but not in electron.
Other cursors also don't work like -webkit-grabbing.

**Comment by RiderSx** [comment] 2016-02-14 17:27
Same issue, any fix?

**Comment by akarupt** [comment] 2016-05-30 03:12
Same here...

**Comment by OlsonDev** [comment] 2016-05-30 04:04
I can hide the cursor in Windows 10.

**Comment by jf908** [comment] 2016-06-06 22:40
I'm currently getting some strange behavior with cursor: none; on Windows 10. I have a webview where the cursor goes invisible if it's set by the preload script but not if it's set by the website itself.

**Comment by matheuss** [comment] 2016-09-03 20:23
I'm also experiencing this. `cursor: -webkit-grab|-webkit-grabbing;` works perfectly on Chrome but not on electron. Any fix/workaround?

**Comment by matheuss** [comment] 2016-09-03 20:29
![cursor](https://cloud.githubusercontent.com/assets/4721750/18227477/f14be2f8-71fb-11e6-93b3-5786969fcb4d.gif)
```html
<div class="title-wrapper" style="cursor: -webkit-grab">
    <p class="title">Placeholder</p>
</div>
```

**Comment by MarshallOfSound** [comment] 2016-09-04 03:15
@matheuss See #5723 regarding the issue you are having

**Comment by matheuss** [comment] 2016-09-04 03:25
Thank you @MarshallOfSound!

**Comment by blashstar** [comment] 2018-11-17 18:06
This works to me:
```
body{
	margin: 0;
	padding: 0;
	overflow: hidden;
	cursor: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=), none;
	user-select: none;
}
```

**Comment by markuslerner** [comment] 2019-10-18 17:02
This worked best for me (overriding cursor for all elements):
```
let css = `* { cursor: ${visible ? 'auto' : 'none'} !important; }`;
win.webContents.insertCSS(css);
```

**Comment by f4z3k4s** [comment] 2022-04-19 11:32
One could use the Pointer Lock API for simplicity. It hides and shows the pointer correctly. Sad thing it doesn't work for DesktopCapturer.

Hide: 

```ts
document.body.requestPointerLock();
```

Show:
```ts
document.exitPointerLock();
```
