### ISSUE TITLE
OSX Dock & will-quit event

### ISSUE THREAD

**Issue by daiyam** [atom/atom-shell#1273] opened 2015-03-21 01:23 UTC
Hi,

It seems that when the *quit* action of the Dock doesn't generate a *will-quit* event.
Unlike the *quit* action of the Menu.

Tested with:
atom-shell v0.22.1
osx 10.9.5

**Comment by zcbenz** [comment] 2015-03-23 01:37
I'm closing this issue because I can not reproduce it, I'll reopen if you can provide a minimal app that shows the problem.

**Closed by zcbenz** 2015-03-23 01:37 UTC
