### ISSUE TITLE
Failed to initialize window's size with `use-content-size` in some case.

### ISSUE THREAD

**Issue by jwu** [atom/atom-shell#1321] opened 2015-03-27 10:16 UTC
I just found window's size will be wrong when setup `use-content-size` with `x` and `y` together. 

When I write:

```javascript
    var mainWindow = new BrowserWindow( {
        title: "Fireball-x",
        width: 800,
        height: 600,
        'use-content-size': true,
        // x: 10,
        // y: 10,
    } );
```

Things are correct, the page-content size will be 600 height and window size will be a little larger than it. But once I put x, y in the options above, `use-content-size` will loose its effect.

I guess this is a bug in atom-shell. I test this in v0.22.2, in Mac OSX. I haven't test this in Windows yet.

**Comment by tommoor** [comment] 2015-03-28 16:32
I believe this is a dupe of https://github.com/atom/atom-shell/issues/996 - albeit with clearer repro steps :smile:

**Comment by zcbenz** [comment] 2015-03-29 10:36
Closing as duplicate of #996, thanks @tommoor!

**Closed by zcbenz** 2015-03-29 10:36 UTC
